### PR TITLE
AsmONE Auto CS (Create Sinus) support

### PR DESCRIPTION
**Pull request by gljubojevic**
I have added support for AsnONE Auto command.
- Currently supports only CS (Create Sinus Command)

## How it works?
After assemble and link
- Parses source files and searches for Auto command
- When Auto command is found commands like CS are parsed and processed
- Binary is updated with result of CS command

To test it you can get forked workspace example containing BlenkVektor.s that is using Auto CS...
https://github.com/gljubojevic/vscode-amiga-wks-example

Initially I was hoping to implement Auto commands on object files before linking but I couldn't figure out how to get symbols in order to insert generated data.
That would be better and cleaner option, however this one works also.

## Other changes 
- Hunk parser extended to keep track of file offsets for later easier exe patching
- Error parser extended to collect source line data for detection of AsmONE specific errors handled by plugin i order to prevent build failure on Auto commands

Hope you will like it :)

### CODE REVIEW

**Comment by prb28** [comment]
Yes, that looks great!
I'll merge this and fix the failing test.
I just have a little request, could you please add some unit tests to you ASMOne class?
I'm trying to stay at 80% of code coverage on new code.

**Comment by gljubojevic** [comment]
Thank you :)

Just pulled your changes, I see what you fixed and it looks like I can ommit this check:
https://github.com/prb28/vscode-amiga-assembly/blob/a10cb596865afb250f682992a7939b576636708b/src/vasm.ts#L418

I'll add test for AsmONE class, how do I run tests?
`
$ npm test
`
I'm asking because this gives me error:
`[main 2019-05-31T06:42:22.506Z] Running extension tests from the command line is currently only supported if no other instance of Code is running.`

And I have only one instance so must be I'm doing something wrong.

**Comment by prb28** [comment]
Yes, you can remove this test line -> my brain was off yesterday when I fixed the test....

There is a launch setting in the debugger to run the tests, it's `Extension tests`. I always use this option.
Otherwise, to do it in a command line you must close the editor before launching `npm test`.

PS: Before running the tests you need a `npm install` (you must have already done it).
PS2: I'll be far from a computer this weekend, so there will be some delay for my answers :-)

**Comment by prb28** [comment]
Oh and thank you for adding the tests, with 3 platforms/OS, it's a really big time saver when coding and releasing!

**Comment by gljubojevic** [comment]
>Yes, you can remove this test line -> my brain was off yesterday when I fixed the test....

Don't worry about it most important part is done :)

Just succeeded to run tests using debugger, that is ok for me to make AsmONE class tests.
I did npm install that is not problem.

>Oh and thank you for adding the tests, with 3 platforms/OS, it's a really big time saver when coding and releasing!

No problem I wanted to have test initially but I couldn't figure out how to run them and didn't want to bother you before I have something to show.

Don't worry about answering during weekend I doubt that I'll have something before next week, enjoy the weekend :)

**Pull request merged**
