### PR TITLE
Add documentation for compiler directives

### PR DESCRIPTION
**Pull request by grahambates**
Include docs for assembler directives aka control words. Adds support for completion and hover help text.

Based on vasm docs with some manual cleanup and formatting.

### CODE REVIEW

**Comment by grahambates** [comment]
Hope you're cool with me bombarding you with PRs! As a long time user of this awesome extension I thought I'd make use of my time over the Xmas break to implement some features I'd like to see.

**Comment by prb28** [comment]
Your PR are great with all the tests updated. So yes, keep on!

**Comment by YannCebron** [comment]
This is a great addition. Would it be possible to "move" it to https://github.com/prb28/m68k-instructions-documentation (I'm already collaborating on these for my plugin https://github.com/YannCebron/m68kplugin) so there would be a single source of truth for all tools? Thanks.

**Comment by prb28** [comment]
With all the work you have done @YannCebron for this documentation, I think it's a good idea to keep it in a shared documentation. I'll do a port of the doc in the other repo.

**Comment by prb28** [comment]
@YannCebron the addition to the other repository is done.

**Comment by YannCebron** [comment]
Thanks, added to my plugin & submitted PR 👍

**Pull request merged**
