### PR TITLE
Integrate stand-alone debug adapter #219

### PR DESCRIPTION
**Pull request by grahambates**
The debugger logic is now in a separate [uae-dap](https://github.com/grahambates/uae-dap/) package, allowing it to be used with other editors that support Microsoft's [Debug Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol/).

In this change I removed all of the logic now handled by the adapter package (along with related tests) and add the package as a dependency. In order to retain VS Code specific functionality, I extend the session classes and override a couple of methods to introduce the required hooks.

As an upshot of these changes, the extension no longer requires the `cstool` binary, as this is included as wasm in the package.

### CODE REVIEW

**Comment by grahambates** [comment]
I still need to test this with WinUAE once I get everything set up on my Windows laptop, but I thought I'd open the PR so you can start having a look.

**Comment by grahambates** [comment]
I'll sort out the failing tests too!

**Comment by prb28** [comment]
Looks good.

Firsts tests, non working features :
- Debug on winuae
- Copper breakpoints

I try to see if I can work on the to projects at the same time.

**Comment by prb28** [comment]
How do you code in the two projects at the same time?

**Comment by grahambates** [comment]
Not sure if this is how you got it working, but I'm using [npm link](https://docs.npmjs.com/cli/v6/commands/npm-link) to link the local package dir. The map files in the out dir should make debugging possible but I don't think I've tried it across both projects.

**Comment by prb28** [comment]
Looks good.
I need some time to test it. I'll merge it when it's done.

**Comment by grahambates** [comment]
Ok cool. I'm doing some testing too and I've just pushed a few more fixes.

In the meantime I've been adding some more features to the debugger. Notably:
- Conditional breakpoints
- Log points
- Custom registers in variables list, including named sub-fields for specific bit ranges
- Additional formats for varaibles, including signed and size variants
- Label offset annotations for address registers

These should should all be present in the current release, which is now linked in this PR. I have some thoughts for more improvements / features that would be good to discuss once this is merged.

**Comment by prb28** [comment]
I had some strange behaviors while debugging, but not on every debug. It needs some more tests.
I think it's good enough for a pre-release, we'll get some feedback here : https://github.com/prb28/vscode-amiga-assembly/discussions/222
We can discuss about your new features in this thread too.
You've added great new features !

**Pull request merged**
